version: "3"
 
services: 
  springapi:
    build:
      context: .     
    image: loanapi:1.0   
    ports:
      - 8082:8080
    depends_on:
      - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar springDockerMongo-0.0.1-SNAPSHOT.jar"
    networks:
      - loanapi-mongo 
      
  mongo: 
     container_name: mongo
     image: mongo     
     ports: 
       - 27017:27017
     networks:
      - loanapi-mongo 
      
  mongo-init:
    build: ./mongo-init
    networks:
      - loanapi-mongo
      
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    networks:
      - loanapi-mongo   
   
networks:
  loanapi-mongo:
   driver: bridge