version: "3"
services:
  consumer:
    build:
      context: .      
    image: consumer
    ports:
      - "8081:8081"
    networks:
      - consumer-producer
    depends_on:
      - producer
 
  producer:
    build:
      context: E:\eclipse_new_workspace\Producer       
    image: producer
    ports:
      - "8080:8080"
    networks:
      - consumer-producer 

networks:
  consumer-producer: